name: flutter_repo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  bruno:  # bruno fork依赖版本 从git中导入
    git:
      url: https://github.com/ligaopeng123-npm/bruno.git
  dio: 5.0.2  # http请求
  provider: 6.0.4 # 状态管理库
  jh_debug: ^1.0.2 # debug定位插件
  ana_page_loop: ^1.0.1 # 路由监听处理埋点
  shared_preferences: 2.0.18 # 持久性存储
  synchronized: 3.0.1 # 多线程安全保护
  ota_update: 4.0.3 # 自动升级
  url_launcher: 6.1.10  # 地址处理
  permission_handler: 10.2.0 # 权限
  cupertino_icons: ^1.0.5  # ios图片
  encrypt: ^5.0.1 # 加密信息
  data_table_2: ^2.4.2 # 表格
  material_floating_search_bar: ^0.3.7  # 高级查询
  animations: ^2.0.7  # 动画相关
  photo_view: ^0.14.0 # 相册预览
  cached_network_image: ^3.2.3 # 图片缓存
  flutter_spinkit: ^5.1.0 # 动画
  intl: ^0.18.0 # 多主题
  easy_refresh: ^3.3.1+2 # 刷新插件
  percent_indicator: ^4.2.3 # 圆环进度插件
  modal_bottom_sheet: 3.0.0-pre # 底部弹窗插件
  flutter_riverpod: ^2.3.6 # AnimationSearchBar插件依赖
  package_info_plus: 3.1.2 #app版本信息
  flutter_watermark: ^1.0.2 # 添加水印信息
  easy_debounce: ^2.0.3 # 去抖
  persistent_bottom_nav_bar_v2: ^4.2.8 # 导航
  flutter_screenutil: ^5.8.4  # 屏幕尺寸自适应
  fluttertoast: ^8.2.2 # 消息弹窗

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/components/
    - asset/images/devices/
    - asset/images/home/
    - asset/images/login/
    - asset/images/updateVersion/header/
    - asset/icons/
    - asset/icons/radio/
    - asset/pem/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: eye_icon
      fonts:
        - asset: asset/fonts/EyeIcon.ttf
    - family: Roboto
      fonts:
        - asset: asset/fonts/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
